/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as StorageRouteImport } from './routes/storage';
import { Route as NetworkRouteImport } from './routes/network';
import { Route as ConsoleRouteImport } from './routes/console';
import { Route as IndexRouteImport } from './routes/index';

const StorageRoute = StorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => rootRouteImport,
} as any);
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any);
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/console': typeof ConsoleRoute;
  '/network': typeof NetworkRoute;
  '/storage': typeof StorageRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/console': typeof ConsoleRoute;
  '/network': typeof NetworkRoute;
  '/storage': typeof StorageRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/console': typeof ConsoleRoute;
  '/network': typeof NetworkRoute;
  '/storage': typeof StorageRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: '/' | '/console' | '/network' | '/storage';
  fileRoutesByTo: FileRoutesByTo;
  to: '/' | '/console' | '/network' | '/storage';
  id: '__root__' | '/' | '/console' | '/network' | '/storage';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  ConsoleRoute: typeof ConsoleRoute;
  NetworkRoute: typeof NetworkRoute;
  StorageRoute: typeof StorageRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/storage': {
      id: '/storage';
      path: '/storage';
      fullPath: '/storage';
      preLoaderRoute: typeof StorageRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/network': {
      id: '/network';
      path: '/network';
      fullPath: '/network';
      preLoaderRoute: typeof NetworkRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/console': {
      id: '/console';
      path: '/console';
      fullPath: '/console';
      preLoaderRoute: typeof ConsoleRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRoute,
  NetworkRoute: NetworkRoute,
  StorageRoute: StorageRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
