/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebRouteImport } from './routes/web'
import { Route as TauriRouteImport } from './routes/tauri'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevtoolsClientIdRouteImport } from './routes/devtools/$clientId'

const WebRoute = WebRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => rootRouteImport,
} as any)
const TauriRoute = TauriRouteImport.update({
  id: '/tauri',
  path: '/tauri',
  getParentRoute: () => rootRouteImport,
} as any)
const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsClientIdRoute = DevtoolsClientIdRouteImport.update({
  id: '/devtools/$clientId',
  path: '/devtools/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/replay': typeof ReplayRoute
  '/tauri': typeof TauriRoute
  '/web': typeof WebRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/replay': typeof ReplayRoute
  '/tauri': typeof TauriRoute
  '/web': typeof WebRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/replay': typeof ReplayRoute
  '/tauri': typeof TauriRoute
  '/web': typeof WebRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/replay' | '/tauri' | '/web' | '/devtools/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/replay' | '/tauri' | '/web' | '/devtools/$clientId'
  id: '__root__' | '/' | '/replay' | '/tauri' | '/web' | '/devtools/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReplayRoute: typeof ReplayRoute
  TauriRoute: typeof TauriRoute
  WebRoute: typeof WebRoute
  DevtoolsClientIdRoute: typeof DevtoolsClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/web': {
      id: '/web'
      path: '/web'
      fullPath: '/web'
      preLoaderRoute: typeof WebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tauri': {
      id: '/tauri'
      path: '/tauri'
      fullPath: '/tauri'
      preLoaderRoute: typeof TauriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools/$clientId': {
      id: '/devtools/$clientId'
      path: '/devtools/$clientId'
      fullPath: '/devtools/$clientId'
      preLoaderRoute: typeof DevtoolsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReplayRoute: ReplayRoute,
  TauriRoute: TauriRoute,
  WebRoute: WebRoute,
  DevtoolsClientIdRoute: DevtoolsClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
