/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevtoolsClientIdRouteImport } from './routes/devtools/$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsClientIdRoute = DevtoolsClientIdRouteImport.update({
  id: '/devtools/$clientId',
  path: '/devtools/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/devtools/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/devtools/$clientId'
  id: '__root__' | '/' | '/devtools/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevtoolsClientIdRoute: typeof DevtoolsClientIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools/$clientId': {
      id: '/devtools/$clientId'
      path: '/devtools/$clientId'
      fullPath: '/devtools/$clientId'
      preLoaderRoute: typeof DevtoolsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevtoolsClientIdRoute: DevtoolsClientIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
