/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReplayRouteImport } from './routes/replay'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModeModeRouteImport } from './routes/mode/$mode'
import { Route as DevtoolsClientIdRouteImport } from './routes/devtools/$clientId'

const ReplayRoute = ReplayRouteImport.update({
  id: '/replay',
  path: '/replay',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeModeRoute = ModeModeRouteImport.update({
  id: '/mode/$mode',
  path: '/mode/$mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DevtoolsClientIdRoute = DevtoolsClientIdRouteImport.update({
  id: '/devtools/$clientId',
  path: '/devtools/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/replay': typeof ReplayRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
  '/mode/$mode': typeof ModeModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/replay': typeof ReplayRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
  '/mode/$mode': typeof ModeModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/replay': typeof ReplayRoute
  '/devtools/$clientId': typeof DevtoolsClientIdRoute
  '/mode/$mode': typeof ModeModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/replay' | '/devtools/$clientId' | '/mode/$mode'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/replay' | '/devtools/$clientId' | '/mode/$mode'
  id: '__root__' | '/' | '/replay' | '/devtools/$clientId' | '/mode/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReplayRoute: typeof ReplayRoute
  DevtoolsClientIdRoute: typeof DevtoolsClientIdRoute
  ModeModeRoute: typeof ModeModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/replay': {
      id: '/replay'
      path: '/replay'
      fullPath: '/replay'
      preLoaderRoute: typeof ReplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode/$mode': {
      id: '/mode/$mode'
      path: '/mode/$mode'
      fullPath: '/mode/$mode'
      preLoaderRoute: typeof ModeModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devtools/$clientId': {
      id: '/devtools/$clientId'
      path: '/devtools/$clientId'
      fullPath: '/devtools/$clientId'
      preLoaderRoute: typeof DevtoolsClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReplayRoute: ReplayRoute,
  DevtoolsClientIdRoute: DevtoolsClientIdRoute,
  ModeModeRoute: ModeModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
